- job:
    name: netlify-sandbox-build-site
    parent: build-javascript-content
    success-url: "site/.vuepress/dist"
    vars:
      javascript_content_dir: "site/.vuepress/dist"
    run: playbooks/build-site/run.yaml

- project:
    check:
      jobs:
        - netlify-sandbox-build-site
    gate:
      jobs:
        - netlify-sandbox-build-site
